'use strict';
const KEY='devotionals-mobile-v1';
const defaults={view:'home',movement:0,started:false,concern:'',volume:35};
let state={...defaults};
try{const stored=JSON.parse(localStorage.getItem(KEY));if(stored&&typeof stored==='object'){state={...defaults,...stored};if(!['home','reading','guide','quiet','closing','ended'].includes(state.view))state.view='home';if(!Number.isInteger(state.movement)||state.movement<0||state.movement>4)state.movement=0;state.concern=String(state.concern||'');state.volume=Math.max(0,Math.min(100,Number(state.volume)||0));}}catch{}
const main=document.querySelector('main'),music=document.querySelector('#music'),notice=document.querySelector('#notice');
const escapeHTML=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));}catch{notice.textContent='Your browser could not save progress. You can continue in this session.';}}
const movements=[
{title:'Arrive',anchor:'Your Father sees in secret.',reference:'Matthew 6:6',prompt:'You have made room to come before your Father. What are you carrying that others may not see? Begin by telling Him honestly why you have come.',more:'You can begin with uncertainty or distraction. There is no need to arrange your thoughts perfectly before speaking to Him.'},
{title:'Worship',anchor:'Our Father which art in heaven, Hallowed be thy name.',reference:'Matthew 6:9 · KJV',prompt:'Consider the One you are approaching. What does His care, holiness or faithfulness bring to mind today? Let that thought become worship and thanks in your own words.',more:'Recall one concrete kindness in your life. Stay with it while it opens into prayer; you do not need to find many things to say.'},
{title:'Respond to the Word',anchor:'Thy will be done in earth, as it is in heaven.',reference:'Matthew 6:10 · KJV',prompt:'Bring one decision before God. What do you hope will happen? Where is it difficult to entrust the outcome to Him? Ask for His help to act according to His Word.',more:'If you need another opening, return to daily bread or forgiveness in the passage. What need can you acknowledge? Is there something to confess or forgiveness to seek?'},
{title:'Pray for someone',anchor:'Give us this day our daily bread.',reference:'Matthew 6:11 · KJV',prompt:'Notice the “us” and “our” in this prayer. Who else is affected by your decision, or has come to mind? Bring their particular needs before God alongside your own.',more:'You may remain with one person. Consider what they are facing and speak plainly about the help they need.'},
{title:'Wait quietly',anchor:'Remain with what you have read.',reference:'Time before God',prompt:'Return to the phrase that has stayed with you. Make room to listen before God. Consider any significant thought in light of Scripture; quiet without a distinct impression is welcome too.',more:'When attention drifts, notice it, gently return to the passage, and continue. A concern may become part of prayer; other tasks can wait.'}
];
const button=(label,action,cls='primary')=>`<button class="${cls}" data-action="${action}">${label}</button>`;
function render(focus=false){const m=movements[state.movement];document.body.classList.toggle('quiet',state.view==='quiet');
if(state.view==='home')main.innerHTML=`<p class="eyebrow">Making room for God each day</p><h1>A little space.<br>Your whole heart.</h1><p class="lede">Read, reflect, and spend time alone with God.</p><div class="card"><span class="eyebrow">Sample devotional · KJV</span><h2>Before you decide</h2><p>Bring your hopes and decisions before your Father.</p><small>Matthew 6:9–13<br>William Branham · The Prophet Elisha</small>${button('Open devotional','reading')}</div>${state.started?button('Continue my prayer','resume','secondary'):''}<p class="hint">A single-day experience prototype for your review. There is no required length and nothing to catch up on.</p><button class="text-button" data-action="settings">Add to your Home Screen</button>`;
if(state.view==='reading')main.innerHTML=`<button class="back" data-action="home">← Today</button><p class="eyebrow">Making room for God each day</p><h1>Before you decide</h1><p class="lede">Bring the decision before God.</p><p class="eyebrow">Matthew 6:9–13 · King James Version</p><blockquote><span class="verse-number">9</span>After this manner therefore pray ye: Our Father which art in heaven, Hallowed be thy name.<br><span class="verse-number">10</span>Thy kingdom come. Thy will be done in earth, as it is in heaven.<br><span class="verse-number">11</span>Give us this day our daily bread.<br><span class="verse-number">12</span>And forgive us our debts, as we forgive our debtors.<br><span class="verse-number">13</span>And lead us not into temptation, but deliver us from evil: For thine is the kingdom, and the power, and the glory, for ever. Amen.</blockquote><hr><p class="eyebrow">A supporting sermon excerpt</p><blockquote>Read the Bible every day. Pray every day. Don't make any decisions too harshly or too quickly, without first considering God about it.</blockquote><small>William Branham · The Prophet Elisha<br>54-0723 · paragraph 10</small><details><summary>About this excerpt</summary><p>This excerpt comes from the source supplied during our design work. The paragraph discusses acting without considering God, daily reading and prayer, and bringing decisions before Him. The devotional's wording and pairing await Paulo's editorial review.</p></details><h2>Pause with the Word</h2><p>Jesus teaches us to bring our needs to the Father and to ask for His will to be done. A decision you face today can become part of that prayer. You can speak honestly about what you hope for while asking for help to act according to His Word.</p><small>Original reflection</small><h2>Bring it into prayer</h2><p>What decision are you carrying today? Tell your Father what you hope will happen, and where you need His direction.</p>${button('Begin with guidance','begin')}${button('Begin in quiet','direct','secondary')}<p class="hint">Stay with a thought as long as you wish. The guide is there when you want it.</p>`;
if(state.view==='guide')main.innerHTML=`<p class="eyebrow">Prayer · ${m.title}</p><h1>${m.title}</h1><blockquote>${m.anchor}</blockquote><small>${m.reference}</small><p class="lede">${m.prompt}</p>${button('Set guide aside','quiet')}<p class="hint">Put the phone down and pray. Your place will be here when you return.</p><details><summary>A little more help</summary><p>${m.more}</p></details><details><summary>Keep a concern nearby</summary><label for="concern">A few words, if helpful</label><textarea id="concern" maxlength="1200" placeholder="Something to bring before God">${escapeHTML(state.concern)}</textarea><small>Saved on this device only. Optional.</small></details>${button(state.movement===4?'Move toward closing':'Next invitation','next','secondary')}<details><summary>Choose a movement</summary><div class="movement-list">${movements.map((x,i)=>`<button data-action="movement" data-index="${i}" aria-current="${i===state.movement}">${x.title}</button>`).join('')}</div></details>${button('Close for today','closing','text-button')}`;
if(state.view==='quiet')main.innerHTML=`<p class="eyebrow">Time alone with God</p><p class="quiet-anchor">${m.anchor}</p><small>${m.reference}</small>${state.concern?`<p class="concern">${escapeHTML(state.concern)}</p>`:''}<div class="quiet-space"></div><p class="hint">There is room to remain.</p><div class="quiet-controls">${button('Return to guidance','guide')}${button('Close for today','closing','text-button')}</div><details><summary>When attention wanders</summary><p>Notice, gently return, continue. Come back to the phrase or concern you were praying about.</p></details>`;
if(state.view==='closing')main.innerHTML=`<p class="eyebrow">When you are ready</p><h1>Carry this<br>into your day.</h1><p class="lede">Give thanks to your Father. Is there one response to carry with you—a decision to bring before Him again, forgiveness to seek, or care to offer someone?</p><p>Close your prayer in your own words, in the name of the Lord Jesus Christ.</p>${button('Leave prayer space','end')}${button('Keep praying','quiet','secondary')}`;
if(state.view==='ended')main.innerHTML=`<p class="eyebrow">Devotionals</p><h1>Make room<br>again tomorrow.</h1><p class="lede">You can return to the passage as your day unfolds.</p>${button('Return to the reading','reading')}${button('Keep praying','resume','secondary')}<p class="hint">This prototype contains one devotional. Return whenever it is useful; there is no completion target.</p>`;
if(focus){window.scrollTo(0,0);main.focus({preventScroll:true});}}
function navigate(view){state.view=view;save();history.pushState({view},'',`#${view}`);render(true)}
function action(name,el){if(name==='settings'){document.querySelector('#settings').showModal();return}if(name==='dismiss'){document.querySelector('#settings').close();return}if(name==='audio'){toggleAudio();return}if(name==='clear'){if(confirm('Clear your saved prayer place and concern on this device?')){music.pause();state={...defaults};save();document.querySelector('#volume').value=35;music.volume=.35;document.querySelector('#settings').close();navigate('home')}return}
if(name==='begin'){state.started=true;state.movement=0;navigate('guide');return}if(name==='direct'){state.started=true;state.movement=2;navigate('quiet');return}if(name==='resume'){state.started=true;navigate('guide');return}if(name==='movement'){state.movement=Number(el.dataset.index);navigate('guide');return}if(name==='next'){if(state.movement<4){state.movement++;navigate('guide')}else navigate('closing');return}if(name==='end'){music.pause();state.started=false;navigate('ended');return}navigate(name)}
document.addEventListener('click',e=>{const el=e.target.closest('[data-action]');if(el)action(el.dataset.action,el)});
document.addEventListener('input',e=>{if(e.target.id==='concern'){state.concern=e.target.value;save()}if(e.target.id==='volume'){state.volume=Number(e.target.value);music.volume=state.volume/100;save()}});
window.addEventListener('popstate',e=>{const v=e.state?.view;if(['home','reading','guide','quiet','closing','ended'].includes(v)){state.view=v;save();render(true)}});
async function toggleAudio(){if(!music.paused){music.pause();return}try{notice.textContent='';await music.play()}catch{notice.textContent='Piano could not start. Connect once to download it, then tap Play piano again.'}}
function audioState(){document.querySelector('#audio-button').textContent=music.paused?'Play piano':'Pause piano';if('mediaSession'in navigator)navigator.mediaSession.playbackState=music.paused?'paused':'playing'}
music.addEventListener('play',audioState);music.addEventListener('pause',audioState);music.addEventListener('error',()=>notice.textContent='Piano is unavailable. You can continue in silence and try again online.');music.volume=state.volume/100;document.querySelector('#volume').value=state.volume;
if('mediaSession'in navigator){navigator.mediaSession.metadata=new MediaMetadata({title:'Piano · Time alone with God',artist:'Devotionals',artwork:[{src:'assets/icon-512.png',sizes:'512x512',type:'image/png'}]});navigator.mediaSession.setActionHandler('play',()=>toggleAudio());navigator.mediaSession.setActionHandler('pause',()=>music.pause());}
let installPrompt;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;document.querySelector('#install').hidden=false});document.querySelector('#install').onclick=async()=>{if(installPrompt){await installPrompt.prompt();installPrompt=null;document.querySelector('#install').hidden=true}};
if('serviceWorker'in navigator){navigator.serviceWorker.register('sw.js').then(()=>navigator.serviceWorker.ready).then(()=>document.querySelector('#offline-status').textContent='Ready for offline use. This devotional and piano recording are saved for this browser.').catch(()=>document.querySelector('#offline-status').textContent='Offline preparation did not finish. Reopen online and try again.')}else document.querySelector('#offline-status').textContent='Offline storage is not supported in this browser.';
history.replaceState({view:state.view},'',`#${state.view}`);render();
